### ISSUE TITLE
ApplicationId is retrieved from a wrong env var?

### ISSUE THREAD

**Issue by programus** [ibm-bluemix-mobile-services/bms-pushnotifications-serversdk-java#3]
`PushNotifications.init(PushNotifications.US_SOUTH_REGION);`

not work when the application running on bluemix. 

The error is

> Error 404: Application xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx not found - check the appId value in the URL path

After some investigation, I found that the applicationId should be the value of `imfpush[0].credentials.appGuid` in `VCAP_SERVICES` instead of `application_id` in `VCAP_APPLICATION` which be used in current source.

**Comment by ManavIBM** [comment]
@programus Hi , This issue is fixed as part of latest SDK release.
