### ISSUE TITLE
Platform JSON format is wrong.

### ISSUE THREAD

**Issue by programus** [ibm-bluemix-mobile-services/bms-pushnotifications-serversdk-java#6]
The platform part of json generated by the SDK is 

    "target": {
      "platforms": [
        {
          "value": "A"
        }
      ]
    }

If I send the JSON, I will get a `FPWSE0004E` error which is an invalid JSON error. 

After some inspection, I found that the correct format should be 

    "target": {
      "platforms": [
        "A"
      ]
    }

instead.

**Comment by srinivasannanduri** [comment]
@programus you seem to be using the "development" branch code? Could you use the "master" branch?

**Comment by programus** [comment]
@srinivasannanduri Thank you for your reply. The code I am using is downloaded automatically by maven since I added the dependency below as what guide said.
```
<dependency>
    <groupId>com.ibm.mobilefirstplatform.serversdk.java</groupId>
    <artifactId>push</artifactId>
    <version>1.0.0</version>
</dependency>
```

**Comment by srinivasannanduri** [comment]
@programus Thanks for your quick reply. I now understand that the maven release is not updated. We shall update it and let you know. Thanks again

**Comment by programus** [comment]
@srinivasannanduri Thank you very much. And I will be appreciate if you could also take a look at another bug I submitted.

**Comment by srinivasannanduri** [comment]
@programus Yes. We're taking a look at both. We will release a consolidated fix soon

**Comment by programus** [comment]
@srinivasannanduri I am very glad to hear this from you. Could you please give me a date of your fix release? Thank you!

**Comment by ManavIBM** [comment]
@programus We released push 1.0.1 SDK with consolidated fix for the two mentioned bugs.
Please include the following dependency below.
<dependency>
		<groupId>com.ibm.mobilefirstplatform.serversdk.java</groupId>
		<artifactId>push</artifactId>
		<version>1.0.1</version>
</dependency>

ThankYou

**Comment by srinivasannanduri** [comment]
@programus ^

**Comment by programus** [comment]
@ManavIBM @srinivasannanduri Thank you very much! I will try recently. And feedback you.
